### ISSUE TITLE
关于训练细节

### ISSUE THREAD

**Issue by htgttuntuntun** [luyukang/DCTNet#1]
您好！我记得您的论文中提到，首先对三个模态的下采样网络进行了预训练，我十分感兴趣，请问您可以透露更多训练细节吗？

**Comment by luyukang** [comment]
三个模态网络的预训练模型中都包括encoder和decoder模块，正常的训练就可以了，你可以看一下那三个model，以及pretrain_depth.py，其他的训练代码与之类似，只是对Spatial.py的训练，多加了DUTS-TR的数据集，你添加一下即可。

**Comment by htgttuntuntun** [comment]
十分感谢您的回复


再次祝好！


| |
宋甲艺
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年11月28日 17:11 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [luyukang/DCTNet] 关于训练细节 (Issue #1) |

三个模态网络的预训练模型中都包括encoder和decoder模块，正常的训练就可以了，你可以看一下那三个model，以及pretrain_depth.py，其他的训练代码与之类似，只是对Spatial.py的训练，多加了DUTS-TR的数据集，你添加一下即可。
